package salon.and.spa.management;


import com.opencsv.CSVWriter;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import salon.and.spa.management.NotGettingBonus;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author HP
 */ 
public class new_menu extends javax.swing.JFrame {

    /**
     * Creates new form new_menu
     */
    public new_menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        item1 = new javax.swing.JTextField();
        item2 = new javax.swing.JTextField();
        total1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBox5 = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jComboBox6 = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jComboBox7 = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        item3 = new javax.swing.JTextField();
        item4 = new javax.swing.JTextField();
        item5 = new javax.swing.JTextField();
        item6 = new javax.swing.JTextField();
        item7 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox9 = new javax.swing.JComboBox<>();
        jComboBox10 = new javax.swing.JComboBox<>();
        jComboBox11 = new javax.swing.JComboBox<>();
        item8 = new javax.swing.JTextField();
        item9 = new javax.swing.JTextField();
        item10 = new javax.swing.JTextField();
        tax = new java.awt.Button();
        vat2 = new javax.swing.JTextField();
        package1 = new javax.swing.JTextField();
        button1 = new java.awt.Button();
        jLabel4 = new javax.swing.JLabel();

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.setLayout(null);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 13)); // NOI18N
        jButton1.setText("TOTAL");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(30, 470, 160, 40);

        item1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item1ActionPerformed(evt);
            }
        });
        jPanel1.add(item1);
        item1.setBounds(800, 90, 170, 40);
        jPanel1.add(item2);
        item2.setBounds(800, 150, 170, 40);

        total1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                total1ActionPerformed(evt);
            }
        });
        jPanel1.add(total1);
        total1.setBounds(200, 470, 150, 40);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2000", "3500", "1000" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(670, 90, 110, 40);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "900", "800", "700", "300" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox2);
        jComboBox2.setBounds(670, 150, 110, 40);

        jLabel7.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("HAIRCUT");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(530, 90, 140, 50);

        jLabel8.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("FACIAL");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(530, 160, 120, 33);

        jLabel9.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Nails");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(530, 210, 110, 33);

        jLabel10.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Massage ");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(530, 280, 190, 33);

        jLabel11.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Threading ");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(530, 330, 200, 50);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "900", "800", "700", "300" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox3);
        jComboBox3.setBounds(670, 210, 110, 40);

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1900", "5800", "7000", "3000" }));
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox4);
        jComboBox4.setBounds(670, 270, 110, 40);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Type-1", "oil massage", "Milk Polish", "Pedicure", "5000"},
                {"Type-2", "Hair Treatment", "Fair Polish", "Manicure", "2500"},
                {"Type-3", "Hait Cut", "Milk Polish", "Both", "4000"},
                {null, null, null, null, null}
            },
            new String [] {
                "Name ", "Hair", "Facial", "Nails", "price"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 160, 490, 80);

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "100", "120" }));
        jComboBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox5ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox5);
        jComboBox5.setBounds(670, 330, 110, 40);

        jLabel12.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Pedicure");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(530, 400, 140, 33);

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "900", "800", "700", "300" }));
        jComboBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox6ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox6);
        jComboBox6.setBounds(670, 390, 110, 40);

        jLabel13.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Makeover");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(530, 460, 140, 33);

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5900", "1800", "2700", "1300" }));
        jComboBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox7ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox7);
        jComboBox7.setBounds(670, 450, 110, 40);

        jLabel14.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Package");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(50, 50, 210, 70);
        jPanel1.add(item3);
        item3.setBounds(800, 210, 170, 40);

        item4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item4ActionPerformed(evt);
            }
        });
        jPanel1.add(item4);
        item4.setBounds(800, 270, 170, 40);
        jPanel1.add(item5);
        item5.setBounds(800, 330, 170, 40);
        jPanel1.add(item6);
        item6.setBounds(800, 390, 170, 40);

        item7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item7ActionPerformed(evt);
            }
        });
        jPanel1.add(item7);
        item7.setBounds(800, 450, 170, 40);

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Menicure");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(530, 530, 110, 33);

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Waxing");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(530, 590, 110, 30);

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Hair Colour ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(530, 50, 150, 33);

        jComboBox9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "900", "800", "700", "300" }));
        jComboBox9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox9ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox9);
        jComboBox9.setBounds(670, 520, 110, 40);

        jComboBox10.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "9000", "8000", "7000", "3000" }));
        jComboBox10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox10ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox10);
        jComboBox10.setBounds(670, 580, 110, 40);

        jComboBox11.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "900", "800", "700", "300" }));
        jComboBox11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox11ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox11);
        jComboBox11.setBounds(670, 40, 110, 40);
        jPanel1.add(item8);
        item8.setBounds(800, 520, 170, 40);
        jPanel1.add(item9);
        item9.setBounds(800, 580, 170, 40);
        jPanel1.add(item10);
        item10.setBounds(800, 30, 170, 40);

        tax.setBackground(new java.awt.Color(255, 255, 255));
        tax.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        tax.setLabel("TAX");
        tax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taxActionPerformed(evt);
            }
        });
        jPanel1.add(tax);
        tax.setBounds(30, 520, 160, 40);
        jPanel1.add(vat2);
        vat2.setBounds(200, 520, 150, 40);

        package1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                package1ActionPerformed(evt);
            }
        });
        jPanel1.add(package1);
        package1.setBounds(20, 120, 220, 30);

        button1.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        button1.setLabel("Confirm");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        jPanel1.add(button1);
        button1.setBounds(110, 580, 180, 60);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salon/and/spa/management/v700batch2-kul-10b-floralframe_1 (1).jpg"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(-10, -20, 1010, 700);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 999, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void package1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_package1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_package1ActionPerformed

    private void taxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taxActionPerformed
        // TODO add your handling code here:

        String text17 = total1.getText();
        if (text17.length() == 0) {
            text17 = "0";
        }
        int val17= Integer.parseInt(text17);
        double vat=550.80;
        double sum1 = val17+vat;
        vat2.setText(Integer.toString((int) sum1));

    }//GEN-LAST:event_taxActionPerformed

    private void jComboBox11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox11ActionPerformed
        // TODO add your handling code here:
        String selectedValue=jComboBox11.getSelectedItem().toString();
        item10.setText(selectedValue);
    }//GEN-LAST:event_jComboBox11ActionPerformed

    private void jComboBox10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox10ActionPerformed
        // TODO add your handling code here:
        String selectedValue=jComboBox10.getSelectedItem().toString();
        item9.setText(selectedValue);
    }//GEN-LAST:event_jComboBox10ActionPerformed

    private void jComboBox9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox9ActionPerformed
        // TODO add your handling code here:
        String selectedValue=jComboBox9.getSelectedItem().toString();
        item8.setText(selectedValue);
    }//GEN-LAST:event_jComboBox9ActionPerformed

    private void item7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_item7ActionPerformed

    private void item4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_item4ActionPerformed

    private void jComboBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox7ActionPerformed
        // TODO add your handling code here:
        String selectedValue=jComboBox7.getSelectedItem().toString();
        item7.setText(selectedValue);
    }//GEN-LAST:event_jComboBox7ActionPerformed

    private void jComboBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox6ActionPerformed
        // TODO add your handling code here:
        String selectedValue=jComboBox6.getSelectedItem().toString();
        item6.setText(selectedValue);
    }//GEN-LAST:event_jComboBox6ActionPerformed

    private void jComboBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox5ActionPerformed
        // TODO add your handling code here:
        String selectedValue=jComboBox5.getSelectedItem().toString();
        item5.setText(selectedValue);
    }//GEN-LAST:event_jComboBox5ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel model=(DefaultTableModel) jTable1.getModel();
        int selectedRowIndex = jTable1.getSelectedRow();

        package1.setText(model.getValueAt(selectedRowIndex,4).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        String selectedValue=jComboBox4.getSelectedItem().toString();
        item4.setText(selectedValue);
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
        String selectedValue=jComboBox3.getSelectedItem().toString();
        item3.setText(selectedValue);
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
        String selectedValue=jComboBox2.getSelectedItem().toString();
        item2.setText(selectedValue);
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        String selectedValue=jComboBox1.getSelectedItem().toString();
        item1.setText(selectedValue);
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void total1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_total1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_total1ActionPerformed

    private void item1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_item1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String text1 = item1.getText();
        if (text1.length() == 0) {
            text1 = "0";
        }
        int val1 = Integer.parseInt(text1);
        String text2 = item2.getText();
        if (text2.length() == 0) {
            text2 = "0";
        }
        int val2 = Integer.parseInt(text2);
        String text3 = item3.getText();
        if (text3.length() == 0) {
            text3 = "0";
        }
        int val3 = Integer.parseInt(text3);
        String text4 = item4.getText();
        if (text4.length() == 0) {
            text4 = "0";
        }
        int val4 = Integer.parseInt(text4);
        String text5 = item5.getText();
        if (text5.length() == 0) {
            text5 = "0";
        }
        int val5 = Integer.parseInt(text5);
        String text6 = item6.getText();
        if (text6.length() == 0) {
            text6 = "0";
        }
        int val6 = Integer.parseInt(text6);
        String text7 = item7.getText();
        if (text7.length() == 0) {
            text7 = "0";
        }
        int val7 = Integer.parseInt(text7);
        String text8 = item8.getText();
        if (text8.length() == 0) {
            text8 = "0";
        }
        int val8 = Integer.parseInt(text8);
        String text9 = item9.getText();
        if (text9.length() == 0) {
            text9 = "0";
        }
        int val9 = Integer.parseInt(text9);
        String text10 = item10.getText();
        if (text10.length() == 0) {
            text10 = "0";
        }
        int val10 = Integer.parseInt(text10);
        
        String text17 = package1.getText();
        if (text17.length() == 0) {
            text17 = "0";
        }
        int val17= Integer.parseInt(text17);
        double sum = val1 + val2+val3 + val4+val5 + val6+val10 + val7+ + val8+ val9+val17;
        total1.setText(Integer.toString((int) sum));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
        new Final_login().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_button1ActionPerformed
     
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
         
    
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(new_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(new_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(new_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(new_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new new_menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private javax.swing.JTextField item1;
    private javax.swing.JTextField item10;
    private javax.swing.JTextField item2;
    private javax.swing.JTextField item3;
    private javax.swing.JTextField item4;
    private javax.swing.JTextField item5;
    private javax.swing.JTextField item6;
    private javax.swing.JTextField item7;
    private javax.swing.JTextField item8;
    private javax.swing.JTextField item9;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox10;
    private javax.swing.JComboBox<String> jComboBox11;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JComboBox<String> jComboBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField package1;
    private java.awt.Button tax;
    private javax.swing.JTextField total1;
    private javax.swing.JTextField vat2;
    // End of variables declaration//GEN-END:variables
}
