
package salon.and.spa.management;
//import com.opencsv.CSVWriter;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;


/**
 *
 * @author HP
 */
public class new_appoinment extends javax.swing.JFrame {

    /**
     * Creates new form new_appoinment
     */
   private int count;
    public new_appoinment() {
        initComponents();
    }
    public void actionPerformed(ActionEvent ae) {
     
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        day = new javax.swing.JTextField();
        month = new javax.swing.JTextField();
        time = new javax.swing.JTextField();
        phone_no = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        SAVE = new javax.swing.JButton();
        NEXT = new javax.swing.JButton();
        valid = new javax.swing.JButton();
        ID1 = new java.awt.TextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 700));
        setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(null);

        jPanel1.setMaximumSize(new java.awt.Dimension(1430, 790));
        jPanel1.setMinimumSize(new java.awt.Dimension(1430, 790));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Edwardian Script ITC", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Book your appointment.");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(310, 20, 410, 50);

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Name");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(270, 80, 160, 30);

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Date");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(270, 160, 110, 40);

        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Time");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(270, 250, 110, 30);

        name.setFont(new java.awt.Font("Tempus Sans ITC", 1, 13)); // NOI18N
        jPanel1.add(name);
        name.setBounds(420, 80, 312, 40);

        jComboBox1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 13)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(510, 140, 94, 24);

        jLabel5.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Day");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(430, 140, 60, 30);

        jLabel6.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Month");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(410, 190, 70, 30);

        jComboBox2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 13)); // NOI18N
        jComboBox2.setMaximumRowCount(24);
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May ", "June", "July", "August ", "September ", "October ", "November ", "December" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jComboBox2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBox2KeyPressed(evt);
            }
        });
        jPanel1.add(jComboBox2);
        jComboBox2.setBounds(510, 190, 100, 24);

        jComboBox4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 13)); // NOI18N
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10 am", "11 am", "12 pm", "1 pm", "3 pm", "4pm", "5 pm", "6 pm", "7 pm", "8 pm", " " }));
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox4);
        jComboBox4.setBounds(510, 250, 94, 24);

        day.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dayActionPerformed(evt);
            }
        });
        jPanel1.add(day);
        day.setBounds(630, 140, 100, 40);

        month.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthActionPerformed(evt);
            }
        });
        jPanel1.add(month);
        month.setBounds(630, 190, 100, 40);
        jPanel1.add(time);
        time.setBounds(650, 250, 80, 22);

        phone_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phone_noActionPerformed(evt);
            }
        });
        phone_no.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                phone_noKeyPressed(evt);
            }
        });
        jPanel1.add(phone_no);
        phone_no.setBounds(450, 290, 280, 40);

        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        jPanel1.add(email);
        email.setBounds(390, 340, 260, 40);

        jLabel9.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Phone number");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(270, 290, 180, 40);

        jLabel10.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Email ");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(270, 340, 120, 40);

        SAVE.setFont(new java.awt.Font("Tempus Sans ITC", 1, 13)); // NOI18N
        SAVE.setText("SAVE");
        SAVE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SAVEActionPerformed(evt);
            }
        });
        SAVE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                SAVEKeyPressed(evt);
            }
        });
        jPanel1.add(SAVE);
        SAVE.setBounds(650, 560, 100, 50);

        NEXT.setFont(new java.awt.Font("Tempus Sans ITC", 1, 13)); // NOI18N
        NEXT.setText("NEXT");
        NEXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NEXTActionPerformed(evt);
            }
        });
        jPanel1.add(NEXT);
        NEXT.setBounds(650, 610, 100, 40);

        valid.setFont(new java.awt.Font("Tempus Sans ITC", 1, 13)); // NOI18N
        valid.setText("Valid");
        valid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validActionPerformed(evt);
            }
        });
        jPanel1.add(valid);
        valid.setBounds(660, 340, 70, 40);

        ID1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ID1ActionPerformed(evt);
            }
        });
        jPanel1.add(ID1);
        ID1.setBounds(460, 400, 270, 50);

        jRadioButton1.setBackground(new java.awt.Color(255, 204, 204));
        jRadioButton1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("GIVE ME A ID");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton1);
        jRadioButton1.setBounds(270, 400, 170, 50);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salon/and/spa/management/v700batch2-kul-13b-floralframe_1.jpg"))); // NOI18N
        jLabel7.setMaximumSize(new java.awt.Dimension(1830, 790));
        jLabel7.setMinimumSize(new java.awt.Dimension(1830, 790));
        jLabel7.setPreferredSize(new java.awt.Dimension(1830, 790));
        jPanel1.add(jLabel7);
        jLabel7.setBounds(0, -10, 1000, 700);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1000, 670);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        String selectedValue=jComboBox1.getSelectedItem().toString();
        day.setText(selectedValue);
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void phone_noKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phone_noKeyPressed
      
          String s=phone_no.getText();
         char[] phone_no1 = s.toCharArray(); 
        
        
        try{
            if(s.length()>11){
                  throw new PhoneNumberOutOfBound("The phone number is too long");
                   
        } }
        catch(PhoneNumberOutOfBound e){
            JOptionPane.showMessageDialog(this,"The phone number is too long",
                        "Error",JOptionPane.ERROR_MESSAGE);
                          
        }
        try{
            for(int i=0;i<s.length();i++){
                if(phone_no1[i]>='a' && phone_no1[i]<='z' &&phone_no1[i]>='A' && phone_no1[i]>='Z'){
                  throw new InvalidPhonenumberException ("Invalid Phone Number");
                }
            }
        }
        
    
        catch(InvalidPhonenumberException e){
             JOptionPane.showMessageDialog(this,"Invalid Phone Number",
                        "Error",JOptionPane.ERROR_MESSAGE);
             phone_no.setText(" ");
        }
    }//GEN-LAST:event_phone_noKeyPressed

    private void NEXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NEXTActionPerformed
        // TODO add your handling code here:
         new new_menu().setVisible (true);
        this.setVisible(false);
    }//GEN-LAST:event_NEXTActionPerformed

    private void SAVEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SAVEActionPerformed
        // TODO add your handling code here:
        String name1=name.getText();
        
        String day1=day.getText();
        String month1=month.getText();
        
        String time1=time.getText();  
        String phone_no1=phone_no.getText();  
        String email_1=email.getText();
        StringBuilder sb2 = new StringBuilder(phone_no1);
        StringBuilder ID=sb2.reverse();
        String primary_key=ID1.getText();
        CSVWriter writer=null;
        Scanner inp= new Scanner(System.in);
        String[] arr= new String[7];
       
       try{
           
          String csv = "sample.csv";
            writer = new CSVWriter(new FileWriter(csv, true));
            
           arr[0]=name1;
           arr[1]=day1;
           arr[2]=month1;
           
           arr[3]=time1;
           arr[4]=phone_no1;
           arr[5]=email_1;
           arr[6]=primary_key;
           writer.writeNext(arr);
           writer.flush();
       }
       catch(IOException ioexception){
           
           ioexception.printStackTrace();
       }
         /*String name1=name.getText()+"\n";
        String day1=day.getText()+"\n";
        String month1=month.getText()+"\n";
        String year1=year.getText()+"\n";
        String time1=time.getText()+"\n";  
        String phone_no1=phone_no.getText()+"\n";  
        String email_1=email.getText()+"\n";
        
            /*JFileChooser fc= new JFileChooser();
            fc.showSaveDialog(this);
            File f=fc.getSelectedFile();
            try{
            FileWriter fw= new FileWriter(f);
            String text=name.getText();
            fw.write(text);
            String date1=date.getText();
            fw.write(date1);
            String time1=time.getText();
            fw.write(time1);
            fw.close();}
            catch(IOException e){
            System.out.println(e);
            }
      

      try {
         
         File f1 = new File("appointments.txt");
         if(!f1.exists()) {
            f1.createNewFile();
         }

         FileWriter fileWritter = new FileWriter(f1.getName(),true);
         BufferedWriter bw = new BufferedWriter(fileWritter);
         bw.write("Name:"+name1);
         bw.write("Day:"+day1);
         bw.write("Month:"+month1);
         bw.write("Month:"+year1);
         bw.write("Month:"+phone_no1);
         bw.write("Month:"+email_1);
         bw.close();
         System.out.println("Done");
      } catch(IOException e){
         e.printStackTrace();
      }*/
        
    }//GEN-LAST:event_SAVEActionPerformed

    private void phone_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phone_noActionPerformed
        // TODO add your handling code here:
      
        
      
    }//GEN-LAST:event_phone_noActionPerformed

    private void validActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validActionPerformed
        // TODO add your handling code here:
          try{
           if (!(Pattern.matches("^[a-zA-Z0-9]+[@]{1}+[a-zA-Z0-9]+[.]{1}+[a-zA-Z0-9]+$", email.getText()))) 
                     throw new InvalidEmailAddress("Invalid Email Address");
            }
       catch (InvalidEmailAddress e){
       JOptionPane.showMessageDialog(null, "Please enter a valid email", "Error", JOptionPane.ERROR_MESSAGE);}

    }//GEN-LAST:event_validActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
        String selectedValue=jComboBox2.getSelectedItem().toString();
        month.setText(selectedValue);
           String day2= day.getText();
        String month2=month.getText();
     
        try{
            if(month2.equals("September") && day2.equals("31")||
                            month2.equals("April") && day2.equals("31")||
                            month2.equals("June") && day2.equals("31")||
                            month2.equals("November") && day2.equals("31")||
                            month2.equals("February") && day2.equals("31")||
                            month2.equals("February") && day2.equals("30"))
                    throw new InvalidDateException("Date is not Valid");
                      
               }
            
           
        catch(InvalidDateException e){
            JOptionPane.showMessageDialog(this,"Invalid Date",
                        "Error",JOptionPane.ERROR_MESSAGE);
                          day.setText(" ");
                          month.setText(" ");
        }
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
        String selectedValue=jComboBox4.getSelectedItem().toString();
        time.setText(selectedValue);
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void SAVEKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SAVEKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_SAVEKeyPressed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        String phone_no1=phone_no.getText(); 
        StringBuffer sb2 = new StringBuffer(phone_no1);
        StringBuffer ID=sb2.reverse();
        ID1.setText(ID.toString());
        
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void ID1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ID1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ID1ActionPerformed

    private void dayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dayActionPerformed
        // TODO add your handling code here:
     
    }//GEN-LAST:event_dayActionPerformed

    private void monthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_monthActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
        /*if (!(Pattern.matches("^[a-zA-Z0-9]+[@]{1}+[a-zA-Z0-9]+[.]{1}+[a-zA-Z0-9]+$", email.getText()))) 
{
            JOptionPane.showMessageDialog(null, "Please enter a valid email", "Error", JOptionPane.ERROR_MESSAGE);
            }
            else
            {
                JOptionPane.showMessageDialog(null, "The email is valid", "Good!", JOptionPane.INFORMATION_MESSAGE);

            }*/
     
        
        
    }//GEN-LAST:event_emailActionPerformed

    private void jComboBox2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox2KeyPressed
        // TODO add your handling code here:
        String selectedValue=jComboBox2.getSelectedItem().toString();
        month.setText(selectedValue);
           String day2= day.getText();
        String month2=month.getText();
     
        try{
            if(month2.equals("September") && day2.equals("31")||
                            month2.equals("April") && day2.equals("31")||
                            month2.equals("June") && day2.equals("31")||
                            month2.equals("November") && day2.equals("31")||
                            month2.equals("February") && day2.equals("31")||
                            month2.equals("February") && day2.equals("30"))
                    throw new InvalidDateException("Date is not Valid");
                      
               }
            
           
        catch(InvalidDateException e){
            JOptionPane.showMessageDialog(this,"Invalid Date",
                        "Error",JOptionPane.ERROR_MESSAGE);
                          day.setText(" ");
                          month.setText(" ");
        }
    }//GEN-LAST:event_jComboBox2KeyPressed

    /**
     * @param args the command line arguments
     */

    /**
     *
     * @param args the command line arguments
     * @throws java.io.IOException
     */
    public static void main(String args[]) throws IOException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(new_appoinment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(new_appoinment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(new_appoinment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(new_appoinment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new new_appoinment().setVisible(true);
                
            }
        });
     
    }
  
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.TextField ID1;
    private javax.swing.JButton NEXT;
    private javax.swing.JButton SAVE;
    private javax.swing.JTextField day;
    private javax.swing.JTextField email;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JTextField month;
    private javax.swing.JTextField name;
    private javax.swing.JTextField phone_no;
    private javax.swing.JTextField time;
    private javax.swing.JButton valid;
    // End of variables declaration//GEN-END:variables
}
